
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - uses: actions/checkout@v1
        - name: Deploy Edgeworkers
          uses: jdmevo123/akamai-edgeworker-action@1.0
          env:
            EDGERC: ${{ secrets.EDGERC }}
          with:
            edgeworkersName: ${{ github.event.repository.name }}
            network: 'staging'
            groupid: '64867' 
